version: "3"
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - .env

  app:
    build: .
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - .:/usr/local/src/webapp/src/
    depends_on:
      - postgres

volumes:
  pg-data:
    driver: local
