version: "3"
services:

  redis:
    image: redis:alpine

  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - .env

  app:
    build: .
    command: >
      sh -c "python3 manage.py migrate &&
            gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - 8000:8000
    env_file:
      - .env
    image: django
    volumes:
      - .:/usr/local/src/webapp/src/
      - static_volume:/usr/local/src/webapp/src/static
    depends_on:
      - postgres

  celery:
    restart: always
    build: .
    env_file:
      - .env
    command: celery -A config worker -l INFO
    volumes:
      - .:/usr/local/src/webapp/src/
    depends_on:
      - postgres
      - redis
      - app

  celery-beat:
    build: .
    env_file:
      - .env
    command: celery -A config beat -l INFO
    volumes:
      - .:/usr/local/src/webapp/src/
    depends_on:
      - postgres
      - redis
      - celery

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/usr/local/src/webapp/src/static
    depends_on:
      - app

volumes:
  pg-data:
    driver: local
  static_volume:
