version: "3"
services:

  redis:
    image: redis:alpine

  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - .env

  app:
    build: .
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - .:/usr/local/src/webapp/src/
    depends_on:
      - postgres

  celery:
    restart: always
    build: .
    env_file:
      - .env
    command: celery -A config worker -l INFO
    volumes:
      - .:/usr/local/src/webapp/src/
    depends_on:
      - postgres
      - redis
      - app

  celery-beat:
    build: .
    env_file:
      - .env
    command: celery -A config beat -l INFO
    volumes:
      - .:/usr/local/src/webapp/src/
    depends_on:
      - postgres
      - redis
      - celery

volumes:
  pg-data:
    driver: local
