# Generated by Django 4.1 on 2022-08-05 08:04

from django.db import migrations, models
import src.core.wishes


class Migration(migrations.Migration):

    dependencies = [
        ("carshowroom", "0008_alter_carshowroom_wishes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carshowroom",
            name="wishes",
            field=models.JSONField(
                blank=True, default=src.core.wishes.default_showroom_wishes
            ),
        ),
    ]
