# Generated by Django 4.0.6 on 2022-08-02 11:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=150)),
                ('location', django_countries.fields.CountryField(max_length=2)),
                ('balance', models.PositiveIntegerField()),
                ('create_time', models.TimeField(auto_now_add=True)),
                ('update_time', models.TimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmission', models.CharField(choices=[('Manual', 'Manual transmission'), ('Auto', 'Automatic transmission')], max_length=50)),
                ('engine_size', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('is_abs', models.BooleanField()),
                ('fuel', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], max_length=20)),
                ('is_parking_sensors', models.BooleanField()),
                ('is_climate_control', models.BooleanField()),
                ('is_cruise_control', models.BooleanField()),
                ('is_heated_seats', models.BooleanField()),
                ('doors', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9)])),
                ('seats', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9)])),
                ('body_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='car_body_type', to='sell.bodytype')),
            ],
        ),
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CarShowroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', django_countries.fields.CountryField(max_length=2)),
                ('balance', models.IntegerField(default=500000)),
                ('create_time', models.TimeField(auto_now_add=True)),
                ('update_time', models.TimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('wish_body_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='showroom_body_type', to='sell.bodytype')),
                ('wish_cars', models.ManyToManyField(blank=True, to='sell.car')),
            ],
        ),
        migrations.CreateModel(
            name='DriveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_type', models.CharField(choices=[('Rear', 'Rear drive'), ('front-wheel', 'front-wheel drive'), ('four-wheel', 'four-wheel drive')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='EngineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', django_countries.fields.CountryField(max_length=2)),
                ('year_foundation', models.IntegerField(validators=[django.core.validators.MinValueValidator(1400), django.core.validators.MaxValueValidator(2023)])),
                ('amount_showrooms', models.PositiveIntegerField()),
                ('create_time', models.TimeField(auto_now_add=True)),
                ('update_time', models.TimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('discount', models.PositiveIntegerField()),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('create_time', models.TimeField(auto_now_add=True)),
                ('update_time', models.TimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cars', models.ManyToManyField(to='sell.car')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_sales_supplier', to='sell.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierCarsPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('create_time', models.TimeField(auto_now_add=True)),
                ('update_time', models.TimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_presence_car', to='sell.car')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_presence_supplier', to='sell.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='CarShowroomSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('discount', models.PositiveIntegerField()),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('create_time', models.TimeField(auto_now_add=True)),
                ('update_time', models.TimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cars', models.ManyToManyField(to='sell.car')),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showroom_sales_showroom', to='sell.carshowroom')),
            ],
        ),
        migrations.CreateModel(
            name='CarShowroomCarsPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('price_per_one', models.PositiveIntegerField()),
                ('create_time', models.TimeField(auto_now_add=True)),
                ('update_time', models.TimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence_showroom_car', to='sell.car')),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence_showroom', to='sell.carshowroom')),
                ('supplier', models.ForeignKey(on_delete=models.SET('supplier deleted'), related_name='presence_showroom_supplier', to='sell.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='CarShowroomBuyers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_amount', models.PositiveIntegerField()),
                ('create_time', models.TimeField(auto_now_add=True)),
                ('update_time', models.TimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyers_buyer', to='sell.buyer')),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyers_showroom', to='sell.carshowroom')),
            ],
        ),
        migrations.AddField(
            model_name='carshowroom',
            name='wish_drive_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='showroom_drive_type', to='sell.drivetype'),
        ),
        migrations.AddField(
            model_name='carshowroom',
            name='wish_engine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='showroom_engine_type', to='sell.enginetype'),
        ),
        migrations.AddField(
            model_name='carshowroom',
            name='wish_supplier',
            field=models.ManyToManyField(blank=True, to='sell.supplier'),
        ),
        migrations.CreateModel(
            name='CarSells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('price_per_one', models.PositiveIntegerField()),
                ('create_time', models.TimeField(auto_now_add=True)),
                ('update_time', models.TimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('buyer', models.ForeignKey(on_delete=models.SET('buyer deleted'), related_name='carsells_buyer', to='sell.buyer')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carsells_car', to='sell.car')),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carsells_showroom', to='sell.carshowroom')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carmodel_brand', to='sell.carbrand')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='drive_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='car_drive_type', to='sell.drivetype'),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='car_engine_type', to='sell.enginetype'),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_model', to='sell.carmodel'),
        ),
        migrations.CreateModel(
            name='BuyerOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_price', models.PositiveIntegerField()),
                ('create_time', models.TimeField(auto_now_add=True)),
                ('update_time', models.TimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_buyer', to='sell.buyer')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_car', to='sell.car')),
            ],
        ),
    ]
